services:
  mongodb:
    image: mongo:latest
    command: --replSet rs0 --quiet
    ports:
      - '127.0.0.1:27017:27017'
    environment:
      MONGO_INITDB_DATABASE: records
    healthcheck:
      # use 'mongo' instead of 'mongosh' if MongoDB version is lower than 5
      test: mongosh --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 2s
      timeout: 3s
      retries: 5

  mongo-init:
    image: mongo:latest
    restart: 'no'
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongosh --host mongodb:27017 --eval
      '
      try {
        rs.initiate( {
           _id : "rs0",
           members: [
              { _id: 0, host: "mongodb:27017" }
           ]
        })
      } catch (e) {
        if (e.codeName === "AlreadyInitialized") {
          print("Replica set already initialized, skipping.");
        } else {
          throw e;
        }
      }
      '

  app:
    build: .
    depends_on:
      mongo-init:
        condition: service_completed_successfully
    environment:
      MONGO_URL: mongodb://mongodb:27017/records?replicaSet=rs0
      PORT: ${PORT:-3000}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
